config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  get 'login', to: 'sessions#new'
  get 'register', to: 'users#new'
  resources :users, except: [:destroy, :index, :new]

  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VoteableBrandon

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates_presence_of :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @post            = Post.find_by(slug: params[:post_id])
    @comment         = @post.comments.new(comment_params)
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    comment = Comment.find(params[:id])
    vote    = current_user.votes.create(voteable: comment, value: params[:upvote] == 'true' ? 1 : -1)

    respond_to do |format|
      format.html do
        if vote.valid?
          flash[:notice] = 'Your vote has been recorded.'
        else
          flash[:error] = 'You have already voted on this comment.'
        end

        redirect_to :back
      end
      format.js do
        if vote.valid?
          success = true
        else
          success = false
        end

        render locals: { comment: comment, vote_success: success }
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_new.html.erb
<%= render 'shared/form_errors', object: @comment %>

<%= form_for [@post, @comment], url: post_comments_path(@post, @comment) do |f| %>
  <div class="control-group">
    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/comments/_show.html.erb
<div class="row">
  <div class="span1 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, upvote: true),
                  method: :post, remote: true, class: 'vote-icon' do %>
        <i class="icon-thumbs-up"></i>
      <% end %>
      <br/>
    <% end %>
    <span id="comment_<%= comment.id %>_votes"><%= pretty_votes(comment) %></span>
    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_comment_path(comment.post, comment, upvote: false),
                  method: :post, remote: true, class: 'vote-icon' do %>
        <i class="icon-thumbs-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span10 well comment">
    <p>
      "<span class="comment-body"><%= "#{comment.body}" %></span>"
      <% if defined?(show_post_link) && show_post_link == true %>
        on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
      <br/>
      <span class="posted-at">
        posted by <%= comment.creator.username %> <%= nice_time(comment.created_at) %>
      </span>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if vote_success %>
$('#comment_<%= comment.id %>_votes').html('<%= pretty_votes(comment) %>');
<% else %>
alert('You have already voted on this comment.');
<% end %>