config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  get 'login', to: 'sessions#new'
  get 'register', to: 'users#new'
  resources :users, except: [:destroy, :index, :new]

  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
end

app/views/shared/_category_link.html.erb
<%
   button_class = case category.id % 7
                  when 0
                    "btn-primary"
                  when 1
                    "btn-info"
                  when 2
                    "btn-success"
                  when 3
                    "btn-warning"
                  when 4
                    "btn-danger"
                  when 5
                    "btn-inverse"
                  when 6
                    ""
                  end
%>
<%= link_to category.name, category_path(category), class: "category-link btn #{button_class}" %>

app/views/shared/_content_title.html.erb
<h4><%= title %></h4>
<hr/>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <div id="error_explanation">
      <h4><%= pluralize(object.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_post.html.erb
<div class="row">
  <div class="well span1 text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, upvote: true),
                  method: :post, remote: true, class: 'vote-icon' do %>
        <i class="icon-thumbs-up"></i>
      <% end %>
      <br/>
    <% end %>
    <span id="post_<%= post.to_param %>_votes"><%= pretty_votes(post) %></span>
    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_path(post, upvote: false),
                  method: :post, remote: true, class: 'vote-icon' do %>
        <i class="icon-thumbs-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="well span10">
    <div class="post">
      <h4><%= link_to post.title, fix_url(post.url) %></h4>

      <p>
        <%= post.description %>
      </p>

      <p>
        <%= link_to pluralize(post.comments.count, 'comment'), post_path(post) %>
      </p>

      <p>
        <% post.categories.each_with_index do |category, index| %>
          <%= render partial: 'shared/category_link', object: category, as: :category %>
        <% end %>
      </p>
    </div>
  </div>
</div>