config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  get 'login', to: 'sessions#new'
  get 'register', to: 'users#new'
  resources :users, except: [:destroy, :index, :new]

  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class="btn-group nav_item">
  <a class="btn btn-small dropdown-toggle"
     data-toggle="dropdown"
     href="#">
    Categories
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <% Category.order("lower(name) ASC").all.each do |category| %>
      <li><a href="<%= category_path(category) %>"><%= "#{category.name}" %></a></li>
    <% end %>
    <% if admin? %>
      <li class="divider"></li>
      <li><a href="<%= new_category_path %>"><i class="icon-plus"></i> New Category</a></li>
    <% end %>
  </ul>
</div>
<% if logged_in? %>
  <div class="nav_item">
    <a class="btn btn-small btn-success" href="<%= new_post_path %>">New Post</a>
  </div>
  <ul class="nav pull-right">
    <li>
      <div class="btn-group nav_item">
        <a class="btn btn-small dropdown-toggle" href="#" data-toggle="dropdown">
          <%= current_user.username %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="<%= edit_user_path(current_user) %>"><i class="icon-pencil"></i> edit profile</a></li>
          <li><a href="<%= user_path(current_user) %>"><i class="icon-user"></i> view profile</a></li>
          <li><a href="<%= logout_path %>"><i class="icon-circle-arrow-left"></i> logout</a></li>
        </ul>
      </div>
    </li>
  </ul>
<% else %>
  <ul class="nav pull-right">
    <li>
      <div class="nav_item">
        <a class="btn btn-small btn-success" href="<%= login_path %>">Login</a>
        <a class="btn btn-small btn-info" href="<%= register_path %>">Register</a>
      </div>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>